accounts/urls.py
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordChangeDoneView,
    PasswordChangeView,
    PasswordResetCompleteView,
    PasswordResetConfirmView,
    PasswordResetDoneView,
    PasswordResetView,
)
from django.urls import path, reverse_lazy

from .views import (
    dashboard,

    NewPasswordChangeView,
    UserProfileView,
    UserRegisterView,
    password_change_done,
)

app_name = "accounts"
urlpatterns = [
    path("dashboard/", dashboard, name="dashboard"),
    path(
        "login/", LoginView.as_view(template_name="accounts/login.html"), name="login"
    ),
    path("register/", UserRegisterView.as_view(), name="register"),

    path(
        "logout/",
        LogoutView.as_view(template_name="accounts/logout.html"),
        name="logout",
    ),
    path("profile/update/", UserProfileView.as_view(), name="profile-update"),
    # password reset
    path("password_change/", NewPasswordChangeView.as_view(), name="password_change"),
    path("password_change/done/", password_change_done,
         name="password_change_done"),
    path(
        "password_reset/",
        PasswordResetView.as_view(
            template_name="accounts/password_reset.html",
            email_template_name='accounts/password_reset_email.html',
            success_url=reverse_lazy('accounts:password_reset_done')),
        name="password_reset",
    ),
    path(
        "password_reset/done/",
        PasswordResetDoneView.as_view(
            template_name="accounts/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name="accounts/password_reset_confirm.html",
            success_url=reverse_lazy('accounts:password_reset_complete')
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        PasswordResetCompleteView.as_view(
            template_name="accounts/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),

]

app/urls.py
from django.urls import path
from .views import (
    NewCategoryView, NewCourseView, NewLessonView,
    NewTopicView, CourseListView, InstructorCourseListView,
    EditCourseView, CourseTopicListView, TopicLessonListView,
    EditLessonView, EditTopicView, CourseDetailView, OrderDetailView
)


app_name = "app"
urlpatterns = [
    path('', CourseListView.as_view(), name="index"),
    path('orders/', OrderDetailView.as_view(), name="user_orders"),
    path('courses/', InstructorCourseListView.as_view(), name="instructor_courses"),
    path('courses/<int:id>/', CourseDetailView.as_view(), name="course_detail"),
    path('courses/<int:id>/topics/',
         CourseTopicListView.as_view(), name="course_topics"),
    path('courses/<int:id>/topics/<int:pk>/edit',
         EditTopicView.as_view(), name="edit_topic"),
    path('courses/<int:id>/topics/<int:pk>/lessons/',
         TopicLessonListView.as_view(), name="topic_lessons"),
    path('courses/<int:id>/topics/<int:pk>/lessons/<int:lesson_id>/edit',
         EditLessonView.as_view(), name="edit_lessons"),
    path('courses/<int:id>/edit/', EditCourseView.as_view(), name="edit_course"),
    path('courses/new_course/', NewCourseView.as_view(), name="new_course"),
    path('categories/new_category/',
         NewCategoryView.as_view(), name="new_category"),
    path('courses/<int:id>/topics/new_topic/',
         NewTopicView.as_view(), name="new_topic"),
    path('courses/<int:id>/topics/<int:pk>/new_lesson/',
         NewLessonView.as_view(), name="new_lesson"),
]

courses/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("unicorn/", include("django_unicorn.urls")),
    path("accounts/", include('accounts.urls')),
    path("", include('app.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

theme/templates/base.html
{% load static tailwind_tags %} {% load unicorn %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Courses: {% block title %}{% endblock title %}</title>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    
    <script
      defer
      src="https://cdn.jsdelivr.net/npm/alpinejs@3.x.x/dist/cdn.min.js"
    ></script>
    {% tailwind_css %} {% unicorn_scripts %}
  </head>

  <body class="leading-normal tracking-normal">
    {% csrf_token %} {% include 'navbar.html' %}
    <div class="container max-w-full">
      {% block content %} {% endblock content %}
    </div>
  </body>
  {% block scripts %} {% endblock scripts %}
</html>

theme/templates/navbar.html
{% load static %}
<div class="w-full bg-blue-700 text-white">
  <div class="max-w-[1024px] h-16 mx-auto flex justify-between items-center">

    <a href="{% url 'app:index' %}" class="text-2xl hover:text-yellow-700 flex"
      ><img style="object-fit: cover;" class="w-30 h-12 text-white" src="{% static 'images/msu-logo.png' %}"><span>Short Courses</span></a
    >
    <div x-data="{showMenu: false}">
      <i @click="showMenu= true" x-show="!showMenu" class="fa-solid fa-bars lg:hidden px-4"></i>
      <i @click= "showMenu= false" x-show= "showMenu" class="fa-solid fa-x lg:hidden px-4"></i>
      <div x-show="showMenu" class="fixed top-16 left-0 h-full w-[40%] border-r flex flex-column ease-in-out duration-500 bg-yellow-700">
      <ul class="lg:hidden">
        <li class="pt-5 px-4 border-b border-gray-600">
          <a
        href="{% url 'accounts:dashboard' %}"
        class="uppercase text-sm font-semibold hover:text-yellow-700"
        ><i class="fa-solid fa-house"></i> Home</a
      >
        </li>
      {% if user.is_authenticated %}
      <li class="pt-5 px-4 border-b border-gray-600"><a
        href="{% url 'accounts:dashboard' %}"
        class=" uppercase text-sm font-semibold hover:text-black"
        ><i class="fa-solid fa-gauge"></i> Dashboard</a
      ></li>
      <li class="pt-5 px-4 border-b border-gray-600">
      <a
        href="{% url 'accounts:logout' %}"
        class=" uppercase text-sm font-semibold hover:text-black"
        ><i class="fa-solid fa-right-from-bracket"></i> logout</a
      ></li>

      {% else %}
      <li class="pt-5 px-4 border-b border-gray-600"><a
        href="{% url 'accounts:register' %}"
        class="px-2 uppercase text-sm font-semibold hover:text-black"
        >register</a
      ></li>
      <li class="pt-5 px-4 border-b border-gray-600"><a
        href="{% url 'accounts:login' %}"
        class="px-2 uppercase text-sm font-semibold hover:text-black"
        ><i class="fa-solid fa-right-to-bracket"></i> Login</a
      ></li>
      {% endif %}
    </ul>
    </div>
    </div>
    
    <ul class="hidden lg:block ">
      <a
        href="{% url 'accounts:dashboard' %}"
        class="px-2 uppercase text-sm font-semibold hover:text-yellow-700"
        >Home</a
      >
      {% if user.is_authenticated %}
      
      <a
        href="{% url 'accounts:dashboard' %}"
        class="px-2 uppercase text-sm font-semibold hover:text-yellow-700"
        >Dashboard</a
      >
      <a
        href="{% url 'accounts:logout' %}"
        class="px-2 uppercase text-sm font-semibold hover:text-yellow-700"
        >logout</a
      >

      {% else %}
      <a
        href="{% url 'accounts:register' %}"
        class="px-2 uppercase text-sm font-semibold hover:text-yellow-700"
        >register</a
      >
      <a
        href="{% url 'accounts:login' %}"
        class="px-2 uppercase text-sm font-semibold hover:text-yellow-700"
        >Login</a
      >
      {% endif %}
    </ul>
  </div>
</div>