accounts/urls.py
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordChangeDoneView,
    PasswordChangeView,
    PasswordResetCompleteView,
    PasswordResetConfirmView,
    PasswordResetDoneView,
    PasswordResetView,
)
from django.urls import path, reverse_lazy

from .views import (
    dashboard,

    NewPasswordChangeView,
    UserProfileView,
    UserRegisterView,
    password_change_done,
)

app_name = "accounts"
urlpatterns = [
    path("dashboard/", dashboard, name="dashboard"),
    path(
        "login/", LoginView.as_view(template_name="accounts/login.html"), name="login"
    ),
    path("register/", UserRegisterView.as_view(), name="register"),

    path(
        "logout/",
        LogoutView.as_view(template_name="accounts/logout.html"),
        name="logout",
    ),
    path("profile/update/", UserProfileView.as_view(), name="profile-update"),
    # password reset
    path("password_change/", NewPasswordChangeView.as_view(), name="password_change"),
    path("password_change/done/", password_change_done,
         name="password_change_done"),
    path(
        "password_reset/",
        PasswordResetView.as_view(
            template_name="accounts/password_reset.html",
            email_template_name='accounts/password_reset_email.html',
            success_url=reverse_lazy('accounts:password_reset_done')),
        name="password_reset",
    ),
    path(
        "password_reset/done/",
        PasswordResetDoneView.as_view(
            template_name="accounts/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name="accounts/password_reset_confirm.html",
            success_url=reverse_lazy('accounts:password_reset_complete')
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        PasswordResetCompleteView.as_view(
            template_name="accounts/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),

]

app/urls.py
from django.urls import path
from .views import (
    NewCategoryView, NewCourseView, NewLessonView,
    NewTopicView, CourseListView, InstructorCourseListView,
    EditCourseView, CourseTopicListView, TopicLessonListView,
    EditLessonView, EditTopicView, CourseDetailView, OrderDetailView
)


app_name = "app"
urlpatterns = [
    path('', CourseListView.as_view(), name="index"),
    path('orders/', OrderDetailView.as_view(), name="user_orders"),
    path('courses/', InstructorCourseListView.as_view(), name="instructor_courses"),
    path('courses/<int:id>/', CourseDetailView.as_view(), name="course_detail"),
    path('courses/<int:id>/topics/',
         CourseTopicListView.as_view(), name="course_topics"),
    path('courses/<int:id>/topics/<int:pk>/edit',
         EditTopicView.as_view(), name="edit_topic"),
    path('courses/<int:id>/topics/<int:pk>/lessons/',
         TopicLessonListView.as_view(), name="topic_lessons"),
    path('courses/<int:id>/topics/<int:pk>/lessons/<int:lesson_id>/edit',
         EditLessonView.as_view(), name="edit_lessons"),
    path('courses/<int:id>/edit/', EditCourseView.as_view(), name="edit_course"),
    path('courses/new_course/', NewCourseView.as_view(), name="new_course"),
    path('categories/new_category/',
         NewCategoryView.as_view(), name="new_category"),
    path('courses/<int:id>/topics/new_topic/',
         NewTopicView.as_view(), name="new_topic"),
    path('courses/<int:id>/topics/<int:pk>/new_lesson/',
         NewLessonView.as_view(), name="new_lesson"),
]

courses/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("unicorn/", include("django_unicorn.urls")),
    path("accounts/", include('accounts.urls')),
    path("", include('app.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.core.validators import RegexValidator
from django.core.exceptions import ValidationError
from django.core.validators import MaxValueValidator, MinValueValidator
from django_countries.fields import CountryField
from django.db import models
import datetime
from django.db.models.signals import post_save
from django.dispatch import receiver
from django_resized import ResizedImageField
# from phonenumber_field.modelfields import PhoneNumberField


class UserAccountManager(BaseUserManager):
    def create_superuser(self, email, first_name, last_name, password=None, **extra_fields):
        if not email:
            raise ValueError("Users must have email")
        if not password:
            raise ValueError("users must have password")
        if not first_name:
            raise ValueError("users must have first_name")
        if not last_name:
            raise ValueError("users must have last_name")

        email = self.normalize_email(email)
        user = self.model(email=email, username=username)
        user.set_password(password)
        extra_fields.setdefault("is_superuser", True)
        user.save()
        return user

    def create_user(self, email, first_name, last_name, password=None):
        if not email:
            raise ValueError("Users must have an email")
        if not password:
            raise ValueError("Users must have a password")
        if not first_name:
            raise ValueError("Users must at least have a first_name ")
        if not last_name:
            raise ValueError("Users must at least have a last_name ")

        email = self.normalize_email(email)
        user = self.model(email=email, first_name=first_name, last_name= last_name)
        user.set_password(password)
        user.save()
        return user


class UserAccount(AbstractBaseUser):

    email = models.EmailField(max_length=255, unique=True)
    first_name = models.CharField(max_length=255, blank=True,null=True)
    last_name= models.CharField(max_length= 255, blank= True, null= True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_admin = models.BooleanField(default=False)

    objects = UserAccountManager()

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["first_name", "last_name"]

    @property
    def full_name(self):
        return f"{self.first_name} {self.last_name}"

    def get_shortname(self):
        return self.first_name

    def is_male(self):
        if self.profile.gender == "male":
            return True
        else:
            return False

    def __str__(self):
        return self.email


national_id_regex = r'^\d{8}[A-Za-z]\d{2}$'
national_id_validator = RegexValidator(
    national_id_regex,
    'Enter a valid national ID. The format should be 8 digits followed by a letter and then 2 digits.'
)


class Profile(models.Model):
    GENDER_CHOICES = (
        ("male", "Male"),
        ("female", "Female"),
        ("other", "Other"),
    )
    MARITAL_STATUS_CHOICES = (
        ("single", "Single"),
        ("married", "Married"),
        ("devorced", "Devorced"),
    )
    bio = models.TextField(null=True, blank=True)
    city = models.CharField(max_length=255, null=True, blank=True)
    dob = models.DateField(blank=True, null=True, validators=[
                           MaxValueValidator(datetime.date.today() - datetime.timedelta(days=5840))])
    gender = models.CharField(
        max_length=10, choices=GENDER_CHOICES, blank=True, null=True)
    marital_status = models.CharField(
        max_length=10, choices=MARITAL_STATUS_CHOICES, blank=True, null=True)
    user = models.OneToOneField(
        UserAccount, on_delete=models.CASCADE, related_name="profile"
    )
    address = models.CharField(max_length=1000, null=True, blank=True)
    nationality = CountryField(blank=True, null=True)
    city = models.CharField(max_length=255, null=True, blank=True)
    national_id = models.CharField(
        max_length=11,
        null=True,
        blank=True,
        unique=True,
        validators=[national_id_validator]
    )
    thumbnail = ResizedImageField(
        size=[200, 200], quality=100, upload_to="authSystem", default="default.jpg"
    )

    class Meta:
        verbose_name = "Profile"
        verbose_name_plural = "Profiles"

    def __str__(self):
        return f"{self.user.username}'s Profile"

    def get_profile_completion(self):
        total_weight = 0
        filled_weight = 0

        # Define the fields that contribute to profile completion with their respective weights
        profile_fields = [
            (self.bio, 2),
            (self.city, 2),
            (self.first_name, 2),
            (self.surname, 2),
            (self.gender, 1),
            (self.marital_status, 1),
            (self.address, 3),
            (self.nationality, 2),
            (self.city, 2),
            (self.national_id, 2),
            (self.thumbnail, 2),
            (self.bio, 2),

        ]

        # Calculate the total weight and filled weight
        for field, weight in profile_fields:
            total_weight += weight
            if field:
                filled_weight += weight

        if self.user.references.exists():
            total_weight += 5
            filled_weight += 5
        else:
            total_weight += 5

        if self.user.experience.exists():
            total_weight += 5
            filled_weight += 5
        else:
            total_weight += 5

        if self.user.academic_qualifications.exists():
            total_weight += 5
            filled_weight += 5
        else:
            total_weight += 5

        if self.user.contacts.exists():
            total_weight += 5
            filled_weight += 5
        else:
            total_weight += 5
        # Calculate the profile completion percentage
        if total_weight > 0:
            completion_percentage = (filled_weight / total_weight) * 100
        else:
            completion_percentage = 0

        return round(completion_percentage, 2)


@receiver(post_save, sender=UserAccount)
def create_profile(sender, created, instance, *args, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=UserAccount)
def save_profile(sender, instance, *args, **kwargs):
    instance.profile.save()

accounts/forms.py
from django import forms
from django_countries.widgets import CountrySelectWidget
from django.contrib.auth.forms import PasswordChangeForm, UserCreationForm

from .models import Profile, UserAccount


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()
    password1 = forms.CharField(
        label="Password",
        strip=False,
        widget=forms.PasswordInput,
    )
    password2 = forms.CharField(
        label="Confirm Password",
        strip=False,
        widget=forms.PasswordInput,
    )
    first_name= forms.CharField(required= True)
    last_name= forms.CharField(required= True)

    class Meta:
        model = UserAccount
        fields = ["first_name", "last_name", "email", "password1", "password2"]


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = UserAccount
        fields = ["email", "first_name", "last_name"]


class ProfileUpdateForm(forms.ModelForm):
    bio = forms.CharField(widget=forms.Textarea(
        attrs={"rows": 3, "placeholder": "Description about yourself", "required": False}))
    dob = forms.DateField(widget=forms.DateInput({
        "type": "date"
    }))
    national_id = forms.CharField(widget=forms.TextInput(
        attrs={"placeholder": "05121587Y05"}
    ))
    address = forms.CharField(widget=forms.TextInput(
        attrs={"placeholder": "3155 Wood Broke North "}
    ))
    city = forms.CharField(widget=forms.TextInput(
        attrs={"placeholder": "Bindura"}
    ))
   

    class Meta:
        model = Profile
        fields = ["dob", "national_id", "gender",
                  "marital_status", "bio", "address", "city", "nationality", "thumbnail"]
        widgets = {"nationality": CountrySelectWidget()}


class CustomPasswordChangeForm(PasswordChangeForm):
    pass

accounts/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import PasswordChangeView
from django.shortcuts import redirect, render, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views import View


from .forms import (
    CustomPasswordChangeForm,
    ProfileUpdateForm,
    UserRegisterForm,
    UserUpdateForm,
)
from .models import Profile, UserAccount


class UserRegisterView(View):
    def get(self, request, *args, **kwargs):
        form = UserRegisterForm()
        return render(request, "accounts/register.html", {"form": form})

    def post(self, request, *args, **kwargs):
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(
                request,
                "Your Account has been created successifully, You can now login!",
            )
            return redirect("accounts:login")
        return render(request, "accounts/register.html", {"form": form})


class UserProfileView(LoginRequiredMixin, View):
    # login_url = '/login/'
    def test_func(self):
        # Define the test function to check if the user is a guest
        return not self.request.user.is_authenticated

    def handle_no_permission(self):
        # Redirect the user if they fail the test
        login_url = reverse(
            "accounts:login"
        )  # Replace 'login' with the URL or name of the login page
        next_url = (
            self.request.get_full_path()
        )  # Get the current URL as the 'next' parameter
        redirect_url = (
            # Append 'next' parameter to the login URL
            f"{login_url}?next={next_url}"
        )
        return redirect(redirect_url)

    def get(self, request, *args, **kwargs):
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)
        context = {"u_form": u_form, "p_form": p_form}
        return render(request, "accounts/profile.html", context)

    def post(self, request, *args, **kwargs):
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(
            request.POST, request.FILES, instance=request.user.profile
        )
        context = {"u_form": u_form, "p_form": p_form}
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(
                request, "You profile has been updated successfully!")
            return redirect("accounts:dashboard")
        messages.warning(request, "Failed to update your profile!")
        return render(request, "accounts/profile.html", context)


@login_required
def dashboard(request):
    
    return render(request, "accounts/dashboard.html")


class NewPasswordChangeView(PasswordChangeView):
    form_class = CustomPasswordChangeForm
    template_name = "accounts/password_change.html"
    success_url = reverse_lazy(
        "accounts:password_change_done"
    )  # URL to redirect after successful password change


def password_change_done(request):
    return render(
        request, "accounts/password_change_done.html", {
            "title": "password change done"}
    )

accounts/templates/accounts/dashboard.html
{% extends "base.html" %} {% load tailwind_filters %} {% block content %}
<!--Tabs navigation-->

<div class="mt-6 max-w-[1024px] mx-auto" x-data="{currentTab: 'Home'}">
  <ul
    class="mb-5 flex list-none flex-row flex-wrap border-b-0 pl-0"
    role="tablist"
    data-te-nav-ref
  >
    <li role="presentation">
      <a
        href="#tabs-home"
        class="my-2 block border-x-0 border-b-2 border-t-0 border-transparent px-7 pb-3.5 pt-4 text-xs font-medium uppercase leading-tight text-neutral-500 hover:isolate hover:border-transparent hover:bg-neutral-100 focus:isolate focus:border-transparent data-[te-nav-active]:border-primary data-[te-nav-active]:text-primary dark:text-neutral-400 dark:hover:bg-transparent dark:data-[te-nav-active]:border-primary-400 dark:data-[te-nav-active]:text-primary-400"
        data-te-toggle="pill"
        data-te-target="#tabs-home"
        data-te-nav-active
        role="tab"
        aria-controls="tabs-home"
        aria-selected="true"
        @click="currentTab= $el.innerHTML"
        >Home</a
      >
    </li>
    <li role="presentation">
      <a
        href="#tabs-profile"
        class="my-2 block border-x-0 border-b-2 border-t-0 border-transparent px-7 pb-3.5 pt-4 text-xs font-medium uppercase leading-tight text-neutral-500 hover:isolate hover:border-transparent hover:bg-neutral-100 focus:isolate focus:border-transparent data-[te-nav-active]:border-primary data-[te-nav-active]:text-primary dark:text-neutral-400 dark:hover:bg-transparent dark:data-[te-nav-active]:border-primary-400 dark:data-[te-nav-active]:text-primary-400"
        data-te-toggle="pill"
        data-te-target="#tabs-profile"
        role="tab"
        aria-controls="tabs-profile"
        aria-selected="false"
        @click="currentTab= $el.innerHTML"
        >Profile</a
      >
    </li>
    <li role="presentation">
      <a
        href="#tabs-settings"
        class="my-2 block border-x-0 border-b-2 border-t-0 border-transparent px-7 pb-3.5 pt-4 text-xs font-medium uppercase leading-tight text-neutral-500 hover:isolate hover:border-transparent hover:bg-neutral-100 focus:isolate focus:border-transparent data-[te-nav-active]:border-primary data-[te-nav-active]:text-primary dark:text-neutral-400 dark:hover:bg-transparent dark:data-[te-nav-active]:border-primary-400 dark:data-[te-nav-active]:text-primary-400"
        data-te-toggle="pill"
        data-te-target="#tabs-settings"
        data-te-nav-active
        role="tab"
        aria-controls="tabs-settings"
        aria-selected="true"
        @click="currentTab= $el.innerHTML"
        >Settings</a
      >
    </li>
  </ul>

  <!--Tabs content-->
  <div class="mb-6">
    <div
      x-show="currentTab=== 'Home'"
      class="hidden opacity-100 transition-opacity duration-150 ease-linear data-[te-tab-active]:block"
      id="tabs-home"
      role="tabpanel"
      aria-labelledby="tabs-home-tab"
      data-te-tab-active
    >
      <div class="shadow p-6">
        <h3 class="text-xl uppercase font-semibold text-gray-500">
          Enrolled Courses
        </h3>
      </div>
    </div>
    <div
      x-show="currentTab === 'Profile'"
      class="opacity-100 transition-opacity duration-150 ease-linear"
      id="tabs-messages"
      role="tabpanel"
      aria-labelledby="tabs-messages-tab"
    >
      <div class="flex shadow p-6">
        <div>
          <img
            class="rounded-full w-20 h-20"
            src="{{ request.user.profile.thumbnail.url }}"
          />
          <div class="mt-[-0.8rem] ml-7">
            <a class="text-teal-700" href="{% url 'accounts:profile-update' %}"
              ><i class="fa-solid fa-pen-to-square"></i
            ></a>
          </div>
        </div>
        <div class="flex-1 ml-4">
          <div class="flex">
            <p class="py-2 text-gray-500 w-2/5">First Name</p>
            <p class="py-2 text-gray-500 w-3/5">
              {{ request.user.first_name}}
            </p>
          </div>
          <div class="flex">
            <p class="py-2 text-gray-500 w-2/5">Last Name</p>
            <p class="py-2 text-gray-500 w-3/5">
              {{ request.user.last_name}}
            </p>
          </div>
          <div class="flex">
            <p class="py-2 text-gray-500 w-2/5">National Id</p>
            <p class="py-2 text-gray-500 w-3/5">
              {{ request.user.profile.national_id}}
            </p>
          </div>
          <div class="flex">
            <p class="py-2 text-gray-500 w-2/5">Gender</p>
            <p class="py-2 text-gray-500 w-3/5">
              {{ request.user.profile.gender}}
            </p>
          </div>
          <div class="flex">
            <p class="py-2 text-gray-500 w-2/5">Marital Status</p>
            <p class="py-2 text-gray-500 w-3/5">
              {{ request.user.profile.marital_status}}
            </p>
          </div>
          <div class="flex">
            <p class="py-2 text-gray-500 w-2/5">Address</p>
            <p class="py-2 text-gray-500 w-3/5">
              {{ request.user.profile.address}}
            </p>
          </div>
          <div class="flex">
            <p class="py-2 text-gray-500 w-2/5">City</p>
            <p class="py-2 text-gray-500 w-3/5">
              {{ request.user.profile.city}}
            </p>
          </div>
          <div class="flex">
            <p class="py-2 text-gray-500 w-2/5">State</p>
            <p class="py-2 text-gray-500 w-3/5">
              {{ request.user.profile.nationality}}
            </p>
          </div>
          <div class="flex">
            <p class="py-2 text-gray-500 w-2/5">Bio</p>
            <p class="py-2 text-gray-500 w-3/5">
              {{ request.user.profile.bio}}
            </p>
          </div>
          <div class="flex">
            <p class="py-2 text-gray-500 w-2/5">Contacts</p>
            <p class="py-2 text-gray-500 w-3/5">
              <span id="contacts"
                >{% include 'accounts/partials/contacts.html' %}</span
              >
            </p>
          </div>
          <div id="add-contact"></div>
        </div>
      </div>
    </div>
    <div
      x-show="currentTab === 'Settings'"
      class="opacity-100 transition-opacity duration-150 ease-linear"
      id="tabs-settings"
      role="tabpanel"
      aria-labelledby="tabs-settings-tab"
    >
      <div class="shadow p-6">
        <a href="{% url 'accounts:password_change' %}" class="text-teal-700"
          >Change Password</a
        >
        <br />
        <a href="{% url 'accounts:logout' %}" class="text-teal-700 py-3"
          >Logout</a
        >
      </div>
    </div>
  </div>
</div>
{% endblock content %}

accounts/templates/accounts/login.html
{% extends "base.html" %} {% load tailwind_filters %} {% block content %}
<div class="max-w-lg mx-auto">
  <form
    method="post"
    class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4 mx-auto"
  >
    <legend class="text-3xl p-4">Welcome Back, Please Login</legend>
    {% csrf_token %}
    <div class="mb-4 flex flex-col">{{ form|crispy }}</div>
    <p class="mb-3">
      <a href="{% url 'accounts:password_reset' %}" class="text-teal-700"
        >Forgot password ?</a
      >
    </p>
    {% include 'app/partials/button.html' with title='login' %}
    <p class="mt-3">
      Don't have an Account?
      <a href="{% url 'accounts:register' %}" class="text-teal-700">Sign Up</a>
    </p>
  </form>
</div>
{% endblock content %}

accounts/templates/accounts/logout.html
{% extends "base.html" %} {% block content %}
<div class="max-w-[600px] mx-auto mt-6">
  <p>
    You are logged out,
    <a class="text-teal-700" href="{% url 'accounts:login' %}">Login now </a>
  </p>
</div>
{% endblock content %}

accounts/templates/accounts/password_change.html
{% extends "base.html" %} {% load tailwind_filters %}{% block content %}
<div class="max-w-lg mx-auto">
  <form
    method="post"
    class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4 mx-auto"
  >
    <legend class="text-3xl mb-3">Change Password</legend>
    {% csrf_token %}
    <div class="mb-4 flex flex-col">{{ form|crispy }}</div>
    {% include 'app/partials/button.html' with title='Change Password' %}
  </form>
</div>
{% endblock content %}

accounts/templates/accounts/password_change_done.html
{% extends "base.html" %} {% block content %}
<div class="w-full mx-auto">
  <h2>Password Changed Successfully</h2>
  <p>Your password has been changed successfully.</p>
</div>
{% endblock content %}

accounts/templates/accounts/password_reset.html
{% extends "base.html" %} {% block content %}
<div class="max-w-[600px] mx-auto">
  <form
    method="post"
    class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4 mx-auto"
  >
    <legend class="text-3xl p-4">Password Reset Request</legend>
    {% csrf_token %}
    <div class="mb-4 flex flex-col">{{ form }}</div>
    {% include 'app/partials/button.html' with title='Request Password Reset' %}
  </form>
</div>
{% endblock content %}

accounts/templates/accounts/password_reset_complete.html
{% extends "base.html" %} {% block content %}
<div class="max-w-xl mx-auto">
  <p>
    Password reset successfull you can now
    <a href="{% url 'accounts:login' %}" class="text-teal-700"> Login </a>
  </p>
</div>
{% endblock content %}

accounts/templates/accounts/password_reset_confirm.html
{% extends "base.html" %} {% load tailwind_filters %} {% block content %}
<div class="max-w-xl mx-auto">
  <form
    method="post"
    class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4 mx-auto"
  >
    <legend class="text-3xl p-4">Password Reset</legend>
    {% csrf_token %}
    <div class="mb-4 flex flex-col">{{ form|crispy }}</div>

    <button
      class="bg-black text-teal-500 hover:text-black hover:bg-teal-500 px-4 py-1 rounded-sm w-full"
    >
      Reset Password
    </button>
  </form>
</div>
{% endblock content %}

accounts/templates/accounts/password_reset_done.html
{% extends "base.html" %} {% block content %}
<div class="max-w-xl mx-auto">
  <h3 class="mb-3">
    An email with instructions to reset your password has been send to your
    email, Thank you
  </h3>
  <a
    href="{% url 'app:index' %}"
    class="bg-black text-blue-700 hover:text-black hover:bg-blue-700 px-4 py-1 rounded-sm"
  >
    Go back home
  </a>
</div>
{% endblock content %}

accounts/templates/accounts/password_reset_email.html
<!DOCTYPE html>
<html>
  <head>
    <title>Password Reset</title>
  </head>
  <body>
    <p>
      You're receiving this email because you requested a password reset for
      your user account at {{ site_name }}.
    </p>
    <p>Please go to the following page and choose a new password:</p>
    <p>
      <a
        href="{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}"
        >Reset Password</a
      >
    </p>
    <p>Your username, in case you’ve forgotten: {{ user.get_username }}</p>
    <p>Thanks for using our site!</p>
    <p>The {{ site_name }} team</p>
  </body>
</html>

accounts/templates/accounts/profile.html
{% extends "base.html" %} {% load tailwind_filters %}{% block content %}
<div class="mx-auto">
  <div class="mt-4 shadow p-4">
    <div class="flex justify-center items-center">
      <img
        class="rounded-full w-20 h-20"
        src="{{ user.profile.thumbnail.url }}"
      />
    </div>
    <div class="mb-5">
      <form
        action="{% url 'accounts:profile-update' %}"
        method="post"
        enctype="multipart/form-data"
      >
        {% csrf_token %}
        <div class="my-5">
          <legend class="text-center border-bottom mb-5">Update Profile</legend>

          <div class="flex flex-col">{{ u_form|crispy }}</div>
          <div class="flex flex-col">{{ p_form|crispy }}</div>
        </div>
        {% include 'app/partials/button.html' with title='Updte Profile' %}
      </form>
    </div>
  </div>
</div>
{% endblock content %}

accounts/templates/accounts/register.html
{% extends "base.html" %}{% load tailwind_filters %} {% block content %}
<div class="max-w-lg mx-auto">
  <form
    method="post"
    class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4 mx-auto"
  >
    <legend class="text-3xl p-4">Join Today</legend>
    {% csrf_token %}
    <div class="mb-4 p-4 flex flex-col">{{ form|crispy }}</div>
    {% include 'app/partials/button.html' with title='register' %}
    <p class="mt-3">
      Already have an Account?
      <a href="{% url 'accounts:login' %}" class="text-teal-700">Login</a>
    </p>
  </form>
</div>
{% endblock content %}