app/urls.py
from django.urls import path
from .views import (
    NewCategoryView, NewCourseView, NewLessonView,
    NewTopicView, CourseListView, InstructorCourseListView,
    EditCourseView, CourseTopicListView, TopicLessonListView,
    EditLessonView, EditTopicView, CourseDetailView, OrderDetailView
)


app_name = "app"
urlpatterns = [
    path('', CourseListView.as_view(), name="index"),
    path('orders/', OrderDetailView.as_view(), name="user_orders"),
    path('courses/', InstructorCourseListView.as_view(), name="instructor_courses"),
    path('courses/<int:id>/', CourseDetailView.as_view(), name="course_detail"),
    path('courses/<int:id>/topics/',
         CourseTopicListView.as_view(), name="course_topics"),
    path('courses/<int:id>/topics/<int:pk>/edit',
         EditTopicView.as_view(), name="edit_topic"),
    path('courses/<int:id>/topics/<int:pk>/lessons/',
         TopicLessonListView.as_view(), name="topic_lessons"),
    path('courses/<int:id>/topics/<int:pk>/lessons/<int:lesson_id>/edit',
         EditLessonView.as_view(), name="edit_lessons"),
    path('courses/<int:id>/edit/', EditCourseView.as_view(), name="edit_course"),
    path('courses/new_course/', NewCourseView.as_view(), name="new_course"),
    path('categories/new_category/',
         NewCategoryView.as_view(), name="new_category"),
    path('courses/<int:id>/topics/new_topic/',
         NewTopicView.as_view(), name="new_topic"),
    path('courses/<int:id>/topics/<int:pk>/new_lesson/',
         NewLessonView.as_view(), name="new_lesson"),
]

courses/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("unicorn/", include("django_unicorn.urls")),
    path("accounts/", include('accounts.urls')),
    path("", include('app.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

app/templates/app/course_detail.html
{% extends 'base.html' %} {% load unicorn %}<!--block content -->
{% block content %} {% unicorn 'cart' user=request.user.pk course=course %}
<!--Endblock content -->
{% endblock content %}

app/templates/app/course_topics.html
{% extends 'base.html' %} {% load tailwind_filters%}{% block content %}
<div class="">
  <div class="flex justify-between mb-3">
    <h2 class="uppercase font-semibold">{{ course.title }} Topics</h2>
    <a
      class="bg-blue-700 px-4 py-2 rounded"
      href="{% url 'app:new_topic' course.id %}"
      >New Topic</a
    >
  </div>
  <table
    class="w-full table-fixed text-sm text-left text-gray-500 dark:text-gray-400 p-4"
  >
    <thead
      class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400"
    >
      <tr>
        <th scope="col" class="w-10/12 px-2 py-3">Topic Title</th>
        <th scope="col" class="w-1/12 px-2 py-3">Edit</th>
        <th scope="col" class="w-1/12 px-2 py-3">delete</th>
      </tr>
    </thead>
    <tbody>
      {% for topic in course.topics.all %}
      <tr
        class="bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600"
      >
        <td class="px-2 py-4">
          <a
            class="text-teal-700"
            href="{% url 'app:topic_lessons' course.id topic.id %}"
            >{{ topic.title}}</a
          >
        </td>
        <td class="px-2 py-4"><i class="fa-solid fa-pen-to-square"></i></td>
        <td class="px-2 py-4"><i class="fa-solid fa-trash"></i></td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock content %}

app/templates/app/index.html
{% extends 'base.html' %} {% load static %} {% block content %}
<section
style="background-image: linear-gradient(to right, rgba(29, 78, 216, 0.8), rgba(149, 58, 204, 0.8), rgba(251, 192, 45, 0.8)), url({% static 'images/learner1.jpg' %})"
  class="h-screen w-full text-center mx-auto flex flex-col bg-cover justify-center bg-gradient-to-r from-blue-700 via-purple-500 to-pink-500"
>
<div class=" max-w-[1024px] mx-auto">
<div class="text-white max-w-[900px]">
  <h2 class="lg:text-5xl text-2xl font-semibold mb-6">Elevate Your Learning Journey with MSU Short Courses</h2>
  <p class="text-xl">Explore a world of knowledge at your fingertips. Join MSU Short Courses and access a diverse range of online courses, expert instructors, and interactive learning experiences. Start your journey to success today!</p>
  <button class="mt-6 bg-yellow-700 p-3 rounded hover:bg-black hover:text-yellow-700">View Course</button>
</div>
<!-- <div class="hidden md:block opacity-70">
  <img class="h-auto max-w-full object-cover" src="{% static 'images/learner.jpg' %}">
</div> -->
  </div>
</section>
<div class="grid p-10 gap-12 md:grid-cols-3 md:p-0 mt-[-3rem] max-w-[1024px] mx-auto">
  <div class="bg-white p-8 shadow my-3">
    <h3 class="text-2xl mb-6 font-semibold text-center">Diverse Course Catalog</h3>
    <p class="text-center">Explore a wide range of courses covering topics from technology to arts, designed to meet your unique learning needs.</p>
  </div>
  <div class="bg-white p-8 shadow my-3">
    <h3 class="text-2xl mb-6 font-semibold text-center">Top-Notch Instructors</h3>
    <p class="text-center">Learn from industry experts and passionate educators who are dedicated to helping you succeed in your learning journey.</p>
  </div>
  <div class="bg-white p-8 shadow my-3">
    <h3 class="text-2xl mb-6 font-semibold text-center">Flexible Learning Options</h3>
    <p class="text-center">Enjoy the freedom to learn at your own pace, on your schedule, with our convenient online courses.</p>
  </div>
</div>
<section class="">
  <div class="flex flex-col justify-center text-center mt-20 my-6 max-w-[600px] mx-auto mb-6">
    <h2 class="lg:text-3xl text-xl text-yellow-500 uppercase font-semibold my-2">
      Our Most Popular Courses
    </h2>
    <p class="">
      Discover our top-rated courses, loved by learners worldwide. Gain in-demand skills and knowledge from our most popular offerings, and join the community of successful learners on their path to growth and achievement.
    </p>
  </div>
  <!-- <div class="my-3 grid grid-cols-3 gap-4 max-w-[1024px] mx-auto">-->
  <div class="max-w-[1024px] mx-auto mt-10">
    {% for course in courses %}
    <!--
      <a
      href="{% url 'app:course_detail' course.id %}"
      class="relative shadow hover:scale-105 hover:transition-all"
    >
      <img
        class="w-full h-44 object-cover"
        src="{{course.featured_image.url}}"
        alt="..."
      />
      <img
        class="absolute right-3 mt-[-2rem] ml-20 w-16 h-16 object-cover rounded-full"
        src="{{course.instructor.profile.thumbnail.url}}"
        alt="..."
      />
      <div class="p-2">
        <p class="text-gray-500">{{course.category.name}}</p>
        <p class="py-2">{{ course.title }}</p>

        <p class="py-1 text-right text-red-500">{{ course.discount }}% off</p>
        <p class="py-1 text-right text-yellow-500">ZWL {{ course.price}}</p>
      </div>
    </a>
    -->
    <div class="my-4">
    <a
      href="{% url 'app:course_detail' course.id %}"
      class="py-10 text-yellow-500 font-semibold uppercase px-3"
      >{{ course.title}}</a
    ></div>

    {% endfor %}
  </div>
</section>
{% endblock content %}

app/templates/app/instructor_courses.html
{% extends 'base.html' %} {% load tailwind_filters%}{% block content %}
<div class="">
  <div class="flex justify-between mb-3">
    <h2 class="uppercase font-semibold">Your Courses</h2>
    <a class="bg-blue-700 px-4 py-2 rounded" href="{% url 'app:new_course' %}"
      >New Course</a
    >
  </div>
  <table
    class="w-full table-fixed text-sm text-left text-gray-500 dark:text-gray-400 p-4"
  >
    <thead
      class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400"
    >
      <tr>
        <th scope="col" class="w-8/12 px-2 py-3">Course Title</th>
        <th scope="col" class="w-2/12 px-2 py-3">Status</th>
        <th scope="col" class="w-1/12 px-2 py-3">Edit</th>
        <th scope="col" class="w-1/12 px-2 py-3">Delete</th>
      </tr>
    </thead>
    <tbody>
      {% for course in courses %}
      <tr
        class="bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600"
      >
        <td class="px-2 py-4">
          <a
            class="text-teal-700"
            href="{% url 'app:course_topics' course.id %}"
            >{{ course.title}}</a
          >
        </td>
        <td class="px-2 py-4">{{ course.status }}</td>
        <td class="px-2 py-4">
          <a href="{% url 'app:edit_course' course.id %}">
            <i class="fa-solid fa-pen-to-square"></i>
          </a>
        </td>
        <td class="px-2 py-4"><i class="fa-solid fa-trash"></i></td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock content %}

app/templates/app/new_category.html
{% extends 'base.html' %} {% load tailwind_filters%}{% block content %}
<div class="">
  <form method="post">
    {% csrf_token %}
    <!---->
    {% include 'app/partials/legend.html' with name="New Category" %}
    <div>{{ form|crispy}}</div>
    <div>
      {% include 'app/partials/button.html' with title='Add Category' %}
    </div>
  </form>
</div>
{% endblock content %}

app/templates/app/new_course.html
{% extends 'base.html' %} {% load tailwind_filters%}{% block content %}
<div class="my-6 max-w-[1024px] mx-auto">
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <!---->
    {% include 'app/partials/legend.html' with name="New Course" %}
    <div>{{ form|crispy}}</div>
    <div>{% include 'app/partials/button.html' with title='Add Course' %}</div>
  </form>
</div>
{% endblock content %}

app/templates/app/new_lesson.html
{% extends 'base.html' %} {% load tailwind_filters%}{% block content %}
<div class="">
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <!---->
    {% include 'app/partials/legend.html' with name="New Lesson" %}
    <div>{{ form|crispy}}</div>
    <div>{% include 'app/partials/button.html' with title='Add Lesson' %}</div>
  </form>
</div>
{% endblock content %}

app/templates/app/new_topic.html
{% extends 'base.html' %} {% load tailwind_filters%}{% block content %}
<div class="">
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <!---->
    {% include 'app/partials/legend.html' with name="New Topic" %}
    <div>{{ form|crispy}}</div>
    <div>{% include 'app/partials/button.html' with title='Add Topic' %}</div>
  </form>
</div>
{% endblock content %}

app/templates/app/topic_lessons.html
{% extends 'base.html' %} {% load tailwind_filters%}{% block content %}
<div class="">
  <div class="flex justify-between mb-3">
    <h2 class="uppercase font-semibold">{{ topic.title }} Lessons</h2>
    <a
      class="bg-blue-700 px-4 py-2 rounded"
      href="{% url 'app:new_lesson' course.id topic.id %}"
      >New Lesson</a
    >
  </div>
  <table
    class="w-full table-fixed text-sm text-left text-gray-500 dark:text-gray-400 p-4"
  >
    <thead
      class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400"
    >
      <tr>
        <th scope="col" class="w-10/12 px-2 py-3">Topic Title</th>
        <th scope="col" class="w-1/12 px-2 py-3">Edit</th>
        <th scope="col" class="w-1/12 px-2 py-3">delete</th>
      </tr>
    </thead>
    <tbody>
      {% for lesson in topic.lessons.all %}
      <tr
        class="bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600"
      >
        <td class="px-2 py-4">
          <a
            class="text-teal-700"
            href="{% url 'app:topic_lessons' course.id topic.id %}"
            >{{ lesson.title}}</a
          >
        </td>
        <td class="px-2 py-4"><i class="fa-solid fa-pen-to-square"></i></td>
        <td class="px-2 py-4"><i class="fa-solid fa-trash"></i></td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock content %}

app/templates/app/user_orders.html
{% extends 'base.html' %}<!--block content -->
{% block content %}
<section class="grid grid-cols-3">
  <div class="col-span-2">
    {% if user_orders %} {% for order in user_orders %}
    <div class="flex justify-between">
      <p>{{ order.course.title }}</p>
      <p>{{ order.course.price }}</p>
    </div>
    {% endfor %}
    <hr />
    <p>Total: {{total}}</p>
    {% endif %}
  </div>
  <div class="mx-6">
    <button class="bg-blue-700 py-2 px-4 rounded">Procced To checkout</button>
  </div>
</section>
<!--Endblock content -->
{% endblock content %}